### ISSUE TITLE
DeprecationWarning while running pytest

### ISSUE THREAD

**Issue by PulkitMishra** [aerospaceresearch/VisMa#136]
Pytest gives the following warning "DeprecationWarning: invalid escape sequence \" on running. Should something be done to handle it or should we ignore it?

**Comment by Alii-Khaled** [comment]
Hello Pulkit, 
I think you should use raw string instead of normal strings to avoid this Warning.
using r'string' instead of 'string' .
I think this will solve this Warning.

**Comment by 8hantanu** [comment]
@PulkitMishra To be specific the above warning is caused due to `\_` (underscore is whitespace). Whitepaces in LaTeX are only rendered if `\` is used before the whitespace. Escape sequence like `\_` don't make any sense in python. Hence using rawstring will make python ignore what is going on inside the string and will interpret the string as is.

**Comment by PulkitMishra** [comment]
Thanks for the input @Alii-Khaled . @8hantanu made a few changes in #135 itself to fix the warnings. Review please.
