### ISSUE TITLE
TypeError on giving fractional powers.

### ISSUE THREAD

**Issue by ZER-0-NE** [aerospaceresearch/VisMa#78]
Currently, Visma does not support fractional exponents.
eg. 4^(4/7) exits giving a type error.

**Comment by alpeshjamgade** [comment]
anyone working on this?

**Comment by 8hantanu** [comment]
@alpeshjamgade  I don't think so. You can go ahead if you want to.

**Comment by lopuka** [comment]
I didn't get the software on internet can anyone help me with this I want to install the software visma 
Please help me with this

**Comment by sidkothiyal** [comment]
@lopuka if you are trying to install visma, please refer to the README on the main page
A simple 

`pip3 install visualmath`

 would work if you have python3 installed

otherwise, you can download the code, 

`chmod +x run` 

`./run install ` 

and then 

`./run visma`

For future please raise a new issue and do not comment on other existing issues.

Thanks

**Comment by alpeshjamgade** [comment]
Use pip install visma                                                                                                                                                                                                                                                                                                                                                     From: Sazid AliSent: Tuesday, March 5, 2019 9:05 AMTo: aerospaceresearch/vismaReply To: aerospaceresearch/vismaCc: Alpesh Jamgade; MentionSubject: Re: [aerospaceresearch/visma] TypeError on giving fractional powers. (#78)I didn't get the software on internet can anyone help me with this I want to install the software visma
Please help me with this

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aerospaceresearch/visma","title":"aerospaceresearch/visma","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/aerospaceresearch/visma"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lopuka in #78: I didn't get the software on internet can anyone help me with this I want to install the software visma \r\nPlease help me with this"}],"action":{"name":"View Issue","url":"https://github.com/aerospaceresearch/visma/issues/78#issuecomment-469523741"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/aerospaceresearch/visma/issues/78#issuecomment-469523741",
"url": "https://github.com/aerospaceresearch/visma/issues/78#issuecomment-469523741",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by vidhanarya** [comment]
If anyone is not working on this issue I would like to work on it

**Comment by mayankDhiman** [comment]
Fixed by #218
